parameters:
#    site_library.example.class: Site\LibraryBundle\Example

services:
#    site_library.example:
#        class: %site_library.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
