parameters:

services:
    admin_global.menu_builder:
        class: Admin\GlobalBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
    admin_global.menu.sidebar:
        class: Knp\Menu\MenuItem
        factory_service: admin_global.menu_builder
        factory_method: createSidebarMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sidebar }
