site_lesson_show:
    pattern:  /show/{index}
    defaults: { _controller: SiteLessonBundle:Lesson:index,index:'html5' }
    options:
        expose: true

site_lesson_category:
    pattern:  /{index}/{page}
    defaults: { _controller: SiteLessonBundle:Default:index,index:'all',page:1}
    requirements:
        page:  \d+  
    options:
        expose: true

site_lesson_pagination:
    pattern:  /pagination/{page_count}/{page}/{lesson_route}/{index}
    defaults: { _controller: SiteLessonBundle:Default:pagination,page:1}
    options:
        expose: true