parameters:
#    site_lesson.example.class: Site\LessonBundle\Example

services:
#    site_lesson.example:
#        class: %site_lesson.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
